name: Badges

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anybadge
        pip install pylint
        pip install pytest
        pip install coverage
    - name: Removing old badges
      run: |
        cd badges
        rm *
        cd ..
    - name: Creating pylint badge
      run: |
        pylint `ls -R | grep .py | xargs` | grep 'Your code has been rated at' | cut -d' ' -f 7 | cut -d'/' -f 1 > pylint.txt
        anybadge --value=$(cat pylint.txt) -f badges/pylint.svg -l pylint 2=red 4=orange 6=yellow 8=yellowgreen 10=green
    - name: Run coverage
      run: |
        coverage run -m pytest
        coverage run -m pytest | grep 'TOTAL'
        coverage run -m pytest | grep 'TOTAL' | tr -s " "
        coverage run -m pytest | grep 'TOTAL' | tr -s " " | cut -d' ' -f 4 
        coverage run -m pytest | grep 'TOTAL' | tr -s " " | cut -d' ' -f 4 > coverage.txt
        echo $(cat coverage.txt)
        anybadge --value=$(cat coverage.txt) -f badges/coverage.svg -l coverage
    - name: Upload badge
      uses: EndBug/add-and-commit@v7
      with:
        message: 'update badges'
        add: 'badges/*.svg'
