name: Pylint Badge

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anybadge
        pip install pylint
    - name: Creating pylint badge
      run: |
        pylint --rcfile=.pylintrc --output-format=text `ls -R|grep .py$|xargs` | tee pylint.txt
        anybadge --value=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt) --file=public/pylint.svg pylint
    - name: Archive pylint results
      uses: actions/upload-artifact@v2
      with:
        name: pylint-badge
        path: public/pylint.svg
