name: Pylint Badge

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install anybadge
        pip install pylint
    - name: Creating pylint badge
      run: |
        rm badges/pylint.svg
        pylint `ls -R|grep .py|xargs` | grep 'Your code has been rated at' | cut -d' ' -f 7 > pylint.txt
        anybadge --value=$(cat pylint.txt) -f badges/pylint.svg pylint
    - name: Upload badge
      uses: EndBug/add-and-commit@v7
      with:
        message: 'update badge'
        add: 'badges/pylint.svg'
